import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { pinoHttp } from 'pino-http';
import { z } from 'zod';
import { drivers, orders, store, users } from './domain/store.js';
import { authenticate, issueToken, permit } from './http/auth.js';
import { haversineKm, optimizeRoute } from './services/optimizer.js';
import { createCheckout, orderIdForRazorpayOrder, paymentMode, verifyRazorpayPayment, verifyRazorpayWebhook } from './services/payments.js';
import { notificationMode, notify } from './services/notifications.js';
import { persistDriver, persistOrder, persistOrderAndDriver, persistenceMode } from './db/persistence.js';
import { syncClerkWebhook } from './services/clerkWebhook.js';
import type { Driver, Order, User } from '@routepulse/shared';
import { allowedWebOrigins } from './config/origins.js';

const coordinate=z.object({label:z.string().min(3).max(160),lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)});
const createSchema=z.object({customerName:z.string().min(2).max(80),customerEmail:z.email(),pickup:coordinate,dropoff:coordinate,packageWeightKg:z.number().positive().max(1000),priority:z.enum(['standard','express','urgent']),amount:z.number().nonnegative().max(1_000_000),currency:z.string().length(3).transform(s=>s.toUpperCase()),promisedAt:z.iso.datetime()});
const statusSchema=z.object({status:z.enum(['pending','assigned','picked_up','in_transit','delivered','failed','cancelled'])});
const driverForTenant=(driver:Driver,tenant:string)=>users.some(user=>user.id===driver.userId&&user.organizationId===tenant);
const canAccessOrder=(user:User,order:Order)=>user.role!=='customer'||order.customerEmail.toLowerCase()===user.email.toLowerCase();
const restore=<T extends object>(target:T,snapshot:T)=>{for(const key of Object.keys(target) as Array<keyof T>)delete target[key];Object.assign(target,structuredClone(snapshot));};
const notifySafely=async(order:Order,template:string)=>{try{return await notify(order,template)}catch(error){console.error(JSON.stringify({event:'notification.enqueue_failed',orderId:order.id,template,error:error instanceof Error?error.message:'Unknown error'}));return{status:'failed',mode:notificationMode()}}};

export function createApp(){
 const app=express(); app.disable('x-powered-by'); app.use(helmet()); app.use(cors({origin:allowedWebOrigins()})); app.use((req,res,next)=>['/api/webhooks/razorpay','/api/webhooks/clerk'].includes(req.path)?express.raw({type:'application/json',limit:'100kb'})(req,res,next):next()); app.use(express.json({limit:'100kb'})); app.use(pinoHttp({redact:['req.headers.authorization']})); app.use('/api',rateLimit({windowMs:60_000,limit:300,standardHeaders:'draft-8',legacyHeaders:false}));
 app.get('/health',(_req,res)=>res.json({status:'ok',persistence:persistenceMode(),queue:notificationMode(),payment:paymentMode(),smtp:Boolean(process.env.GOOGLE_SMTP_USER&&process.env.GOOGLE_SMTP_APP_PASSWORD),timestamp:new Date().toISOString()}));
 app.post('/api/auth/demo',(req,res)=>{const parsed=z.object({role:z.enum(['admin','dispatcher','driver','customer'])}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid role',details:parsed.error.issues});const user=users.find(u=>u.role===parsed.data.role)!;return res.json({token:issueToken(user),user});});
 app.get('/api/track/:code',(req,res)=>{const order=orders.find(o=>o.trackingCode===req.params.code);if(!order)return res.status(404).json({error:'Tracking code not found'});const driver=drivers.find(d=>d.id===order.assignedDriverId);return res.json({trackingCode:order.trackingCode,customerName:order.customerName.split(' ')[0],status:order.status,priority:order.priority,destination:order.dropoff.label,driver:driver?{name:driver.name.split(' ')[0],location:driver.location,lastSeenAt:driver.lastSeenAt}:null,promisedAt:order.promisedAt,updatedAt:order.updatedAt,events:order.events.map(({type,message,createdAt})=>({type,message,createdAt}))});});
 app.post('/api/webhooks/razorpay',async(req,res)=>{const raw=Buffer.isBuffer(req.body)?req.body:Buffer.from('');const signature=String(req.header('x-razorpay-signature')||'');if(!verifyRazorpayWebhook(raw,signature))return res.status(400).json({error:'Invalid Razorpay webhook signature'});try{const body=JSON.parse(raw.toString('utf8')) as {event?:string;payload?:{payment?:{entity?:{order_id?:string;notes?:{routepulseOrderId?:string}}};order?:{entity?:{id?:string;notes?:{routepulseOrderId?:string}}}}};const entity=body.payload?.payment?.entity;const providerOrder=entity?.order_id||body.payload?.order?.entity?.id;const localId=entity?.notes?.routepulseOrderId||body.payload?.order?.entity?.notes?.routepulseOrderId||(providerOrder?orderIdForRazorpayOrder(providerOrder):undefined);if(localId){const order=orders.find(o=>o.id===localId);if(order&&['payment.captured','order.paid'].includes(body.event||'')&&order.paymentStatus!=='paid'){const snapshot=structuredClone(order);order.paymentStatus='paid';order.updatedAt=new Date().toISOString();try{await persistOrder(order)}catch(error){restore(order,snapshot);throw error}await notifySafely(order,'payment_received')}}return res.status(200).json({received:true})}catch(error){if(error instanceof SyntaxError)return res.status(400).json({error:'Invalid webhook payload'});throw error}});
 app.post('/api/webhooks/clerk',async(req,res,next)=>{try{const raw=Buffer.isBuffer(req.body)?req.body:Buffer.from('');return res.json(await syncClerkWebhook(raw,{'svix-id':req.header('svix-id')||undefined,'svix-timestamp':req.header('svix-timestamp')||undefined,'svix-signature':req.header('svix-signature')||undefined}))}catch(e){next(e)}});
 app.use('/api',authenticate);
 app.get('/api/me',(req,res)=>res.json(req.user));
 app.get('/api/orders',(req,res)=>{let data=store.listOrders(req.user!.organizationId);if(req.user!.role==='driver'){const driver=drivers.find(d=>d.userId===req.user!.id);data=data.filter(o=>o.assignedDriverId===driver?.id)}if(req.user!.role==='customer')data=data.filter(o=>o.customerEmail===req.user!.email);const status=req.query.status;if(typeof status==='string')data=data.filter(o=>o.status===status);return res.json(data);});
 app.post('/api/orders',permit('admin','dispatcher'),async(req,res,next)=>{let order:Order|undefined;try{const input=createSchema.parse(req.body);order=store.createOrder(input,req.user!);await persistOrder(order);await notifySafely(order,'order_created');return res.status(201).json(order)}catch(e){if(order){const index=orders.indexOf(order);if(index>=0)orders.splice(index,1)}next(e)}});
 app.get('/api/orders/:id',(req,res)=>{const order=store.getOrder(req.params.id,req.user!.organizationId);if(!order)return res.status(404).json({error:'Order not found'});if(!canAccessOrder(req.user!,order))return res.status(403).json({error:'Not your order'});if(req.user!.role==='driver'){const d=drivers.find(x=>x.userId===req.user!.id);if(order.assignedDriverId!==d?.id)return res.status(403).json({error:'Not your assignment'})}return res.json(order)});
 app.patch('/api/orders/:id/status',permit('admin','dispatcher','driver'),async(req,res,next)=>{try{const {status}=statusSchema.parse(req.body);const order=store.getOrder(req.params.id,req.user!.organizationId);if(!order)return res.status(404).json({error:'Order not found'});if(req.user!.role==='driver'){const d=drivers.find(x=>x.userId===req.user!.id);if(order.assignedDriverId!==d?.id)return res.status(403).json({error:'Not your assignment'})}const driver=drivers.find(x=>x.id===order.assignedDriverId);const orderSnapshot=structuredClone(order),driverSnapshot=driver?structuredClone(driver):undefined;try{store.transition(order,status,req.user!);if(driver&&driver.status!==driverSnapshot?.status)await persistOrderAndDriver(order,driver);else await persistOrder(order)}catch(error){restore(order,orderSnapshot);if(driver&&driverSnapshot)restore(driver,driverSnapshot);throw error}await notifySafely(order,`order_${status}`);req.app.get('io')?.to(`tenant:${req.user!.organizationId}`).emit('order:updated',order);req.app.get('io')?.to(`track:${order.trackingCode}`).emit('order:updated',order);return res.json(order)}catch(e){next(e)}});
 app.post('/api/orders/:id/assign',permit('admin','dispatcher'),async(req,res,next)=>{try{const order=store.getOrder(req.params.id,req.user!.organizationId);if(!order)return res.status(404).json({error:'Order not found'});const eligible=drivers.filter(d=>driverForTenant(d,req.user!.organizationId)&&d.status==='available'&&d.capacityKg>=order.packageWeightKg);const driver=req.body.driverId?eligible.find(d=>d.id===req.body.driverId):eligible.sort((a,b)=>haversineKm(a.location,order.pickup)-haversineKm(b.location,order.pickup))[0];if(!driver)return res.status(422).json({error:'No eligible available driver'});const orderSnapshot=structuredClone(order),driverSnapshot=structuredClone(driver);try{store.assign(order,driver,req.user!);await persistOrderAndDriver(order,driver)}catch(error){restore(order,orderSnapshot);restore(driver,driverSnapshot);throw error}await notifySafely(order,'driver_assigned');req.app.get('io')?.to(`tenant:${req.user!.organizationId}`).emit('order:updated',order);return res.json(order)}catch(e){next(e)}});
 app.get('/api/drivers',permit('admin','dispatcher'),(req,res)=>res.json(drivers.filter(driver=>driverForTenant(driver,req.user!.organizationId))));
 app.post('/api/routes/optimize',permit('admin','dispatcher'),(req,res,next)=>{try{const body=z.object({driverId:z.string(),orderIds:z.array(z.string()).min(1).max(50)}).parse(req.body);const driver=drivers.find(d=>d.id===body.driverId&&driverForTenant(d,req.user!.organizationId));if(!driver)return res.status(404).json({error:'Driver not found'});const selected=body.orderIds.map(id=>store.getOrder(id,req.user!.organizationId)).filter(Boolean);if(selected.length!==body.orderIds.length)return res.status(404).json({error:'One or more orders not found'});return res.json(optimizeRoute(driver.location,selected.map(o=>({...o!.dropoff,id:o!.id,demandKg:o!.packageWeightKg})),driver.capacityKg))}catch(e){next(e)}});
 app.post('/api/payments/:orderId/checkout',permit('admin','dispatcher','customer'),async(req,res,next)=>{try{const order=store.getOrder(req.params.orderId,req.user!.organizationId);if(!order)return res.status(404).json({error:'Order not found'});if(!canAccessOrder(req.user!,order))return res.status(403).json({error:'Not your order'});return res.json(await createCheckout(order))}catch(e){next(e)}});
 app.post('/api/payments/:orderId/verify',permit('admin','dispatcher','customer'),async(req,res,next)=>{try{const order=store.getOrder(req.params.orderId,req.user!.organizationId);if(!order)return res.status(404).json({error:'Order not found'});if(!canAccessOrder(req.user!,order))return res.status(403).json({error:'Not your order'});if(order.paymentStatus==='paid')return res.json(order);const input=z.object({razorpayOrderId:z.string(),razorpayPaymentId:z.string(),razorpaySignature:z.string()}).parse(req.body);if(!verifyRazorpayPayment(order.id,input.razorpayOrderId,input.razorpayPaymentId,input.razorpaySignature))return res.status(400).json({error:'Payment verification failed'});const snapshot=structuredClone(order);order.paymentStatus='paid';order.updatedAt=new Date().toISOString();order.events.push({id:crypto.randomUUID(),type:'payment',message:'Razorpay payment verified',actorId:req.user!.id,createdAt:order.updatedAt});try{await persistOrder(order)}catch(error){restore(order,snapshot);throw error}await notifySafely(order,'payment_received');return res.json(order)}catch(e){next(e)}});
 app.post('/api/payments/demo/:orderId/confirm',permit('admin','dispatcher','customer'),async(req,res,next)=>{try{if(paymentMode()!=='demo')return res.status(404).json({error:'Demo payment disabled'});const order=store.getOrder(req.params.orderId,req.user!.organizationId);if(!order)return res.status(404).json({error:'Order not found'});if(!canAccessOrder(req.user!,order))return res.status(403).json({error:'Not your order'});if(order.paymentStatus==='paid')return res.json(order);const snapshot=structuredClone(order);order.paymentStatus='paid';order.updatedAt=new Date().toISOString();order.events.push({id:crypto.randomUUID(),type:'payment',message:'Payment confirmed by demo adapter',actorId:req.user!.id,createdAt:order.updatedAt});try{await persistOrder(order)}catch(error){restore(order,snapshot);throw error}await notifySafely(order,'payment_received');return res.json(order)}catch(e){next(e)}});
 app.get('/api/analytics/summary',permit('admin','dispatcher'),(req,res)=>res.json(store.summary(req.user!.organizationId)));
 app.use((_req,res)=>res.status(404).json({error:'Route not found'}));
 app.use((err:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{if(err instanceof z.ZodError)return res.status(400).json({error:'Validation failed',details:err.issues});const e=err as Error&{status?:number};return res.status(e.status||500).json({error:e.status?e.message:'Internal server error'});}); return app;
}
