import 'dotenv/config';
import { createServer } from 'node:http';
import { Server } from 'socket.io';
import { createApp } from './app.js';
import { configureSockets } from './realtime/socket.js';
import { closeNotifications } from './services/notifications.js';
import { initializePersistence } from './db/persistence.js';
import { closeDb } from './db/client.js';
import { allowedWebOrigins } from './config/origins.js';
import { configurationStatus, warnOnConfigurationDrift } from './config/runtime.js';
import { initializeRouteRuns } from './services/routeRuns.js';
const boot=async()=>{await initializePersistence();await initializeRouteRuns();const app=createApp(),server=createServer(app);const io=new Server(server,{cors:{origin:allowedWebOrigins()}});app.set('io',io);configureSockets(io);const port=Number(process.env.PORT||4000);server.listen(port,()=>console.info(`RoutePulse API listening on http://localhost:${port}`));
warnOnConfigurationDrift();
if (process.env.STRICT_CONFIG === 'true' && !configurationStatus().ready) throw new Error(`RoutePulse configuration is incomplete: ${configurationStatus().missing.join(', ')}`);
const shutdown=()=>server.close(async()=>{io.close();await closeNotifications();await closeDb();process.exit(0)});process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
}; boot().catch(error=>{console.error('RoutePulse startup failed',error);process.exit(1)});
