import { describe,expect,it } from 'vitest';import { canTransition } from '../src/domain/stateMachine.js';import { haversineKm,optimizeRoute } from '../src/services/optimizer.js';
import { roleFromClerkClaims } from '../src/services/clerkIdentity.js';
import { estimateEta } from '../src/services/eta.js';
import { organizationSettings, settingsForOrganization } from '../src/domain/store.js';
describe('order state machine',()=>{it('permits the happy path and blocks skipping custody',()=>{expect(canTransition('pending','assigned')).toBe(true);expect(canTransition('pending','delivered')).toBe(false);expect(canTransition('delivered','in_transit')).toBe(false)})});
describe('optimizer',()=>{it('calculates known distance and returns every stop',()=>{expect(haversineKm({lat:0,lng:0},{lat:0,lng:1})).toBeCloseTo(111.19,1);const result=optimizeRoute({lat:12.97,lng:77.59},[{id:'a',label:'A',lat:12.98,lng:77.6,demandKg:2},{id:'b',label:'B',lat:12.96,lng:77.58,demandKg:3}],10);expect(result.stops.map(s=>s.id).sort()).toEqual(['a','b']);expect(result.distanceKm).toBeGreaterThan(0);expect(result.stops[0].arrivalAt).toEqual(expect.any(String))});it('respects service time, a return leg, and a route limit',()=>{const result=optimizeRoute({lat:0,lng:0},[{id:'a',label:'A',lat:0,lng:0.01,demandKg:1}],10,{averageSpeedKph:60,serviceMinutes:10,returnToDepot:true,maxRouteMinutes:30});expect(result.durationMinutes).toBe(13);expect(result.returnToDepot).toBe(true);expect(()=>optimizeRoute({lat:0,lng:0},[{id:'a',label:'A',lat:0,lng:1}],10,{averageSpeedKph:60,maxRouteMinutes:30})).toThrow(/exceeds/)});it('rejects an overloaded vehicle',()=>{expect(()=>optimizeRoute({lat:0,lng:0},[{id:'a',label:'A',lat:1,lng:1,demandKg:11}],10)).toThrow(/exceeds/)});it('flags a windowed stop that cannot meet its promise',()=>{const start='2026-01-01T08:00:00.000Z';const result=optimizeRoute({lat:0,lng:0},[{id:'a',label:'A',lat:0,lng:0.1,promisedAt:'2026-01-01T08:10:00.000Z',deliveryWindowStart:'2026-01-01T08:05:00.000Z'}],10,{startAt:start,averageSpeedKph:60,serviceMinutes:5});expect(result.algorithm).toContain('time-window');expect(result.stops[0].lateRisk).toBe(true);expect(result.warnings).toHaveLength(1)})});
describe('eta',()=>{it('uses the delivery window and reports stale location confidence',()=>{const now=Date.parse('2026-01-01T08:00:00.000Z');const order={status:'in_transit',priority:'standard',pickup:{label:'A',lat:0,lng:0},dropoff:{label:'B',lat:0,lng:0.01},promisedAt:'2026-01-01T08:20:00.000Z',deliveryWindowStart:'2026-01-01T08:15:00.000Z'} as any;const eta=estimateEta(order,{location:{lat:0,lng:0},lastSeenAt:'2026-01-01T07:30:00.000Z'} as any,{averageSpeedKph:60} as any,now);expect(eta.estimatedArrivalAt).toBe('2026-01-01T08:15:00.000Z');expect(eta.etaConfidence).toBe('low');expect(eta.locationAgeSeconds).toBe(1800)})});
describe('Clerk role mapping',()=>{it('uses free public metadata roles before organization roles',()=>{expect(roleFromClerkClaims({public_metadata:{role:'dispatcher'},org_role:'org:member'})).toBe('dispatcher');expect(roleFromClerkClaims({metadata:{role:'driver'}})).toBe('driver')});it('supports the default Clerk admin role and safely defaults to customer',()=>{expect(roleFromClerkClaims({org_role:'org:admin'})).toBe('admin');expect(roleFromClerkClaims({role:'owner'})).toBe('customer')})});
describe('organization settings',()=>{it('keeps tenant settings isolated from the showcase tenant',()=>{const tenant=settingsForOrganization('org_test_isolated');tenant.name='Acme Fleet';expect(tenant.organizationId).toBe('org_test_isolated');expect(organizationSettings.name).not.toBe('Acme Fleet')})});
